carrier_a = [
    "Auto",
    "Cyber Liability",
    "Directors & Officers",
    "Employment Practices Liability",
    "Errors & Omissions",
    "Excess Policy",
    "General Liability",
    "Homeowners",
    "Individual Health",
    "Inland Marine",
    "Professional Liability",
    "Property",
    "Umbrella",
    "Flood",
    "Dwelling Fire",
    "Mobile Home",
    "Businessowners Policy",
    "Boat",
    "Earthquake",
    "Garage",
    "Fire",
    "Bond",
    "Workers Compensation",
    "State Farm",
    "GEICO",
    "Allstate",
    "Progressive",
    "Farmers Insurance",
    "Nationwide",
    "Liberty Mutual",
    "American Family Insurance",
    "Travelers",
    "USAA",
    "MetLife",
    "The Hartford",
    "Chubb",
    "Zurich North America",
    "CNA Insurance",
    "AIG (American International Group)",
    "Berkshire Hathaway (GUARD Insurance Companies)",
    "Hiscox",
    "Markel Corporation",
    "UnitedHealthcare",
    "Anthem",
    "Aetna",
    "Cigna",
    "Humana",
    "Kaiser Permanente",
    "Blue Cross Blue Shield",
    "Molina Healthcare",
    "Centene Corporation",
    "Health Care Service Corporation (HCSC)",
    "New York Life",
    "Northwestern Mutual",
    "Prudential Financial",
    "MassMutual",
    "Lincoln Financial Group",
    "Transamerica",
    "John Hancock",
    "Principal Financial Group",
    "Guardian Life",
    "Chubb",
    "Beazley",
    "Foremost Insurance Group",
    "American Modern Insurance Group",
    "Wright Flood",
    "California Earthquake Authority (CEA)",
    "RLI Insurance Company",
    "Safeco Insurance",
    "PURE Insurance",
    "Lemonade Insurance",
    "Assurant",
    "Erie Insurance",
    "Auto-Owners Insurance",
    "Sentry Insurance",
    "Amica Mutual Insurance",
    "Infinity Insurance",
    "American National Insurance",
    "First American"
]

carrier_b = [
    "AIG",
    "All Risks Limited",
    "Allstate",
    "American Modern Insurance",
    "AmGUARD",
    "AmTrust Financial Services, Inc.",
    "AmWINS Access Insurance",
    "AmWINS Brokerage",
    "Apogee Insurance Group",
    "Arch Insurance Company",
    "Arthur J. Gallagher",
    "ASI (American Strategic Insurance)",
    "Attune",
    "Bass Underwriters",
    "Berkley Asset Protection",
    "Berkley Regional Specialty Insurance Company",
    "Berkshire Hathaway Inc.",
    "Bold Penguin",
    "Breckenridge Insurance Services",
    "Burns & Wilcox",
    "Chesapeake Employers Insurance",
    "CannGen Insurance Services",
    "Chubb",
    "CID Insurance Programs",
    "Cincinnati Insurance",
    "Clearcover Insurance Company",
    "CNA Surety",
    "Colonial Surety Company",
    "COVER Financial",
    "Cowbell Insurance",
    "Crum & Forster Specialty Insurance Company",
    "CRC Group Wholesale & Specialty",
    "Donegal",
    "ECC Insurance Brokers, LLC",
    "Employers Insurance Company of Nevada",
    "Encompass Insurance",
    "Everguard Insurance",
    "FIRST CONNECT",
    "FISIF-Food Industry Self-Insurance Fund",
    "Foremost",
    "Front Row Insurance",
    "GIG Insurance Group",
    "Hartford",
    "HBW (Hull & Company)",
    "Hiscox",
    "IBIS-Independent Bankers Insurance Services",
    "IIAA Agency Administrative Services, Inc.",
    "Insential Inc.",
    "Insurance Solutions Group",
    "International Excess",
    "Irwin Siegel Agency, Inc.",
    "Kinsale Insurance",
    "Kelly Klee",
    "Kemper",
    "Kentucky Employers' Mutual Insurance",
    "Liberty Mutual",
    "Mesa Underwriters Specialty Insurance",
    "Markel Insurance Company",
    "Mercer Insurance Group",
    "Mercury County Mutual - TX",
    "Mercury Insurance",
    "MetLife Auto & Home®",
    "Mountain States Mutual Casualty Company",
    "National Fire Insurance of Hartford",
    "National Program Administrators",
    "Nationwide Insurance",
    "Neptune",
    "NETWORKED | AMWINS DAIS",
    "New Heights Insurance Solutions",
    "NEW MEXICO FAIR PLAN",
    "New Mexico Mutual Casualty Company",
    "NEXT Insurance",
    "NFP Property & Casualty Services, Inc.",
    "Ohio Casualty",
    "One Beacon",
    "Orchid",
    "Pathpoint",
    "Penn National Insurance",
    "PEACHTREE SPECIAL RISK BROKERS, LLC",
    "Philadelphia Insurance Company",
    "PIE Insurance",
    "Preferred Employers Insurance Company",
    "Privilege Underwriters Reciprocal Exchange (PURE)",
    "Progressive Insurance",
    "PROPELLER BONDS",
    "QBE Insurance Corporation",
    "Redpoint County Mutual Company",
    "Risk Exchange Insurance Services, Inc.",
    "Risk Placement Service",
    "RLI Insurance Company",
    "RLI Surety",
    "Ryan Turner Specialty",
    "Starstone National Insurance",
    "Safeco Insurance",
    "SELECTIVE INSURANCE GROUP INC.",
    "Smart Choice Agents",
    "Southwest Insurance Group",
    "SPECIAL MARKETS INSURANCE CONSULTANTS",
    "Specialty Market Insurance Consultants, Inc.",
    "State Auto Insurance",
    "Stillwater Insurance Services, Inc.",
    "Surety Placement Services, LLC",
    "TAPCO Underwriters Inc.",
    "Texas Mutual",
    "The Hartford",
    "Thimble Insurance Services",
    "Topa Insurance Company",
    "TransGuard Insurance Company of America, Inc.",
    "Travelers",
    "Travelers Texas MGA",
    "Union Standard Insurance Group",
    "US Assure",
    "USLI",
    "Virtus Insurance",
    "Western Pacific Insurance Network, Inc.",
    "Western Pacific Mutual Insurance Company",
    "Wright National Flood Insurance Company",
    "Zurich"
]

lob = [
    "Auto",
    "Cyber Liability",
    "Directors & Officers",
    "Employment Practices Liability",
    "Errors & Omissions",
    "Excess Policy",
    "General Liability",
    "Homeowners",
    "Individual Health",
    "Inland Marine",
    "Professional Liability",
    "Property",
    "Umbrella",
    "Flood",
    "Dwelling Fire",
    "Mobile Home",
    "Businessowners Policy",
    "Boat",
    "Earthquake",
    "Garage",
    "Fire",
    "Bond",
    "Workers Compensation"
]


carrier_c = [item for item in carrier_a if item not in lob]

carrier_d = list(set(carrier_b + carrier_c))

#print("Updated list_a:", result)

#print("Combined list with duplicates removed:", carrier_d)

semifinal_list = ['CNA Surety', 'American Modern Insurance Group', 'New Heights Insurance Solutions', 
'NEW MEXICO FAIR PLAN', 'Redpoint County Mutual Company', 'AmTrust Financial Services, Inc.', 
'CRC Group Wholesale & Specialty', 'Lemonade Insurance', 'Burns & Wilcox', 'Kinsale Insurance', 'Employers Insurance Company of Nevada', 
'Risk Exchange Insurance Services, Inc.', 'MetLife', 'Centene Corporation', 'Kelly Klee', 'Chesapeake Employers Insurance', 'GIG Insurance Group', 
'Smart Choice Agents', 'Insential Inc.', 'AIG (American International Group)', 'Crum & Forster Specialty Insurance Company', 'Mesa Underwriters Specialty Insurance', 
'Risk Placement Service', 'Clearcover Insurance Company', 'PROPELLER BONDS', 'All Risks Limited', 'MetLife Auto & Home®', 'One Beacon', 
'US Assure', 'TAPCO Underwriters Inc.', 'Cincinnati Insurance', 'Breckenridge Insurance Services', 'Liberty Mutual', 'RLI Insurance Company', 
'Virtus Insurance', 'Wright National Flood Insurance Company', 'Pathpoint', 'Lincoln Financial Group', 'Kaiser Permanente', 'Kemper', 'AmGUARD', 
'Philadelphia Insurance Company', 'Principal Financial Group', 'Arch Insurance Company', 'Encompass Insurance', 'Molina Healthcare', 'Transamerica', 
'Insurance Solutions Group', 'Colonial Surety Company', 'International Excess', 'Thimble Insurance Services', 'Safeco Insurance', 'Berkshire Hathaway (GUARD Insurance Companies)', 
'Berkley Asset Protection', 'Bass Underwriters', 'CNA Insurance', 'Mercer Insurance Group', 'GEICO', 'Arthur J. Gallagher', 'Berkley Regional Specialty Insurance Company', 
'RLI Surety', 'State Auto Insurance', 'Mercury Insurance', 'FIRST CONNECT', 'Zurich', 'John Hancock', 'California Earthquake Authority (CEA)', 'Markel Insurance Company', 
'National Fire Insurance of Hartford', 'Berkshire Hathaway Inc.', 'Beazley', 'New York Life', 'SELECTIVE INSURANCE GROUP INC.', 'NEXT Insurance', 'QBE Insurance Corporation', 
'National Program Administrators', 'Foremost', 'American National Insurance', 'Stillwater Insurance Services, Inc.', 'USLI', 'Anthem', "Kentucky Employers' Mutual Insurance", 
'Assurant', 'Western Pacific Insurance Network, Inc.', 'Ohio Casualty', 'NFP Property & Casualty Services, Inc.', 'ECC Insurance Brokers, LLC', 'TransGuard Insurance Company of America, Inc.', 
'State Farm', 'Northwestern Mutual', 'NETWORKED | AMWINS DAIS', 'First American', 'Hiscox', 'Union Standard Insurance Group', 
'MassMutual', 'Aetna', 'Mountain States Mutual Casualty Company', 'Auto-Owners Insurance', 'Topa Insurance Company', 'CID Insurance Programs', 
'Everguard Insurance', 'Irwin Siegel Agency, Inc.', 'AmWINS Access Insurance', 'Blue Cross Blue Shield', 'USAA', 'Preferred Employers Insurance Company', 
'Starstone National Insurance', 'Front Row Insurance', 'Amica Mutual Insurance', 'Southwest Insurance Group', 'PURE Insurance', 'IIAA Agency Administrative Services, Inc.', 
'Western Pacific Mutual Insurance Company', 'Zurich North America', 'Allstate', 'Ryan Turner Specialty', 'CannGen Insurance Services', 'Foremost Insurance Group', 'Chubb', 'Texas Mutual', 
'Penn National Insurance', 'American Modern Insurance', 'American Family Insurance', 'Nationwide', 'PIE Insurance', 'UnitedHealthcare', 'Health Care Service Corporation (HCSC)', 
'Surety Placement Services, LLC', 'Infinity Insurance', 'Neptune', 'Apogee Insurance Group', 'Travelers Texas MGA', 'Farmers Insurance', 'FISIF-Food Industry Self-Insurance Fund', 
'Bold Penguin', 'COVER Financial', 'HBW (Hull & Company)', 'Mercury County Mutual - TX', 'Markel Corporation', 'AmWINS Brokerage', 'Nationwide Insurance', 'Erie Insurance', 
'IBIS-Independent Bankers Insurance Services', 'Attune', 'Wright Flood', 'Cowbell Insurance', 'AIG', 'Privilege Underwriters Reciprocal Exchange (PURE)', 'Sentry Insurance', 
'Travelers', 'ASI (American Strategic Insurance)', 'PEACHTREE SPECIAL RISK BROKERS, LLC', 'Orchid', 'Prudential Financial', 'Humana', 'SPECIAL MARKETS INSURANCE CONSULTANTS', 
'The Hartford', 'Hartford', 'Specialty Market Insurance Consultants, Inc.', 'Donegal', 'Guardian Life', 'Progressive', 'Progressive Insurance', 'New Mexico Mutual Casualty Company', 
'Cigna']

#count_final_list = len(final_list)

#print(count_final_list)

semifinal_list_2 = [
    "21st Century Insurance",
    "Acuity Insurance",
    "Aflac",
    "Allianz Life",
    "Allied Insurance",
    "Allstate",
    "American Automobile Association (AAA)",
    "American Family Insurance",
    "American Income Life Insurance Company",
    "American International Group (AIG)",
    "American National Insurance Company",
    "American Strategic Insurance (ASI)",
    "Ameriprise Auto & Home Insurance",
    "Ameriprise Financial",
    "Ameritas Life Insurance Company",
    "Amica Mutual Insurance",
    "Amtrust Financial Services",
    "Applied Underwriters",
    "Arbella Insurance Group",
    "Assurant",
    "Assurity Life Insurance Company",
    "Auto-Owners Insurance",
    "AXA Equitable Life Insurance Company",
    "Bankers Life and Casualty Company",
    "Berkshire Hathaway",
    "Brotherhood Mutual Insurance Company",
    "CareSource",
    "Chubb Corp",
    "Citizens Property Insurance Corporation",
    "CNA Financial",
    "CNO Financial Group",
    "Colonial Life & Accident Insurance Company",
    "Combined Insurance",
    "Commerce Insurance Group",
    "Country Financial",
    "Delta Dental",
    "Encompass Insurance Company",
    "Erie Insurance Group",
    "Esurance",
    "Evergreen USA RRG",
    "Farmers Insurance Group",
    "Federated Mutual Insurance Company",
    "First Insurance Company of Hawaii",
    "FM Global",
    "Fortegra Group",
    "GAINSCO",
    "GEICO",
    "General Re",
    "Genworth Financial",
    "Gerber Life Insurance Company",
    "Globe Life And Accident Insurance Company",
    "GMAC Insurance",
    "Gracy Title Company",
    "Grange Mutual Casualty Company",
    "The Guardian Life Insurance Company of America",
    "GuideOne Insurance",
    "Hagerty Insurance Agency",
    "Hanover Insurance",
    "The Hartford",
    "HCC Insurance Holdings",
    "Hiscox Small Business Insurance",
    "Horace Mann Educators Corporation",
    "Ironshore",
    "K&K Insurance",
    "Kansas City Life Insurance Company",
    "Kemper Corporation",
    "Knights of Columbus",
    "Lemonade (insurance)",
    "Liberty Mutual",
    "Lincoln National Corporation",
    "Manhattan Life Insurance Company",
    "Markel Corporation",
    "MassMutual",
    "Merchants Insurance Group",
    "Mercury Insurance Group",
    "MetLife",
    "Metromile",
    "Modern Woodmen of America",
    "Mutual of Omaha",
    "National Flood Insurance Program",
    "Nationwide Mutual Insurance Company",
    "New Jersey Manufacturers Insurance Company",
    "New York Life Insurance Company",
    "NJM Insurance Group",
    "The Norfolk & Dedham Group",
    "Northwestern Mutual",
    "Omega",
    "Oxford Health Plans",
    "Pacific Life",
    "PEMCO",
    "Penn Mutual",
    "Penn National Insurance",
    "Philadelphia Contributionship for the Insurance of Houses from Loss by Fire",
    "Philadelphia Insurance Companies",
    "Physicians Mutual",
    "Primerica",
    "Principal Financial Group",
    "Progressive",
    "ProSight Specialty Insurance",
    "Protective Life",
    "Prudential Financial",
    "Pure Insurance",
    "QBE",
    "The Regence Group",
    "Reliance Insurance Company",
    "Reliance Partners",
    "RLI Corp.",
    "Safe Auto Insurance Company",
    "Safeco",
    "Safeway Insurance Group",
    "Securian Financial Group",
    "Sentry Insurance",
    "Shelter Insurance",
    "Society Insurance",
    "Southern Aid and Insurance Company",
    "SquareTrade",
    "Standard Insurance Company",
    "State Automobile Mutual Insurance Company",
    "State Farm Insurance",
    "Sun Life Financial",
    "Symetra",
    "The General",
    "The Travelers Companies",
    "TIAA",
    "Titan Insurance Company",
    "Transamerica Corporation",
    "Tricare",
    "Trupanion",
    "UPC Insurance",
    "Unum",
    "USAA",
    "West Coast Life",
    "Western & Southern Financial Group",
    "Western Mutual Insurance Group",
    "Westfield Insurance",
    "White Mountains Insurance Group",
    "W. R. Berkley Corporation",
    "XL Catlin",
    "Zurich Insurance Group",
    "Aflac",
    "Allianz Life",
    "Allstate",
    "American Family Insurance",
    "American Fidelity Assurance",
    "American Income Life Insurance Company",
    "Ameritas Life Insurance Company",
    "Amica Mutual Insurance",
    "Assurity Life Insurance Company",
    "AXA Equitable Life Insurance Company",
    "Bankers Life and Casualty",
    "Banner Life Insurance Company",
    "Colonial Life & Accident Insurance Company",
    "Colonial Penn",
    "Conseco",
    "Farmers Insurance Group",
    "Garden State Life",
    "Genworth Financial",
    "The Great-West Life Assurance Company",
    "Gerber Life Insurance Company",
    "Globe Life And Accident Insurance Company",
    "The Guardian Life Insurance Company of America",
    "Horace Mann Educators Corporation",
    "ING Group",
    "Jackson National Life",
    "John Hancock Life Insurance",
    "Kansas City Life Insurance Company",
    "Lincoln National Corporation",
    "Manhattan Life Insurance Company",
    "MEGA Life and Health Insurance",
    "MetLife",
    "Mutual of Omaha",
    "National Life Group",
    "National Western Life Insurance Company",
    "Nationwide Mutual Insurance Company",
    "New York Life Insurance Company",
    "Ohio National Financial Services Company",
    "Pacific Life",
    "Physicians Mutual",
    "Primerica",
    "Protective Life",
    "Prudential Financial",
    "Securian Financial Group",
    "Standard Insurance Company",
    "State Farm Insurance",
    "Thrivent",
    "TIAA-CREF",
    "Transamerica Corporation",
    "UNIFI Companies",
    "United of Omaha",
    "Western & Southern Financial Group",
    "AARP",
    "Aetna",
    "American National Insurance Company",
    "Amerigroup",
    "Blue Cross and Blue Shield Association",
    "Bright Health",
    "CareSource",
    "Cambia Health Solutions",
    "Centene Corporation",
    "Cigna",
    "Compass Rose Benefits Group",
    "Delta Dental",
    "Elevance Health",
    "EmblemHealth",
    "Fallon Health",
    "Geisinger",
    "Golden Rule Insurance Company",
    "Harvard Pilgrim Health Care",
    "Health Net",
    "HealthMarkets",
    "HealthPartners",
    "Highmark",
    "Humana",
    "Independence Blue Cross",
    "Kaiser Permanente",
    "Kaleida Health",
    "MassHealth",
    "Medical Mutual of Ohio",
    "Molina Healthcare",
    "Oscar Health",
    "Oxford Health Plans",
    "Premera Blue Cross",
    "Principal Financial Group",
    "Shelter Insurance",
    "State Farm",
    "Thrivent Financial for Lutherans",
    "UnitedHealth Group",
    "Unitrin",
    "WellCare",
    "Aetna",
    "American Family Insurance",
    "Bankers Life and Casualty",
    "CareSource",
    "Conseco",
    "Fidelis Care",
    "Kaiser Permanente",
    "Mutual of Omaha",
    "Physicians Mutual",
    "Premera Blue Cross",
    "Thrivent Financial for Lutherans",
    "United American Insurance Company",
    "Accident Fund Insurance Company of America",
    "American International Group (AIG)",
    "AmTrust Financial Services",
    "Cincinnati Financial Corporation",
    "Erie Insurance Group",
    "GUARD Insurance Group",
    "Hanover Insurance",
    "The Hartford",
    "Liberty Mutual",
    "Merchants Insurance Group",
    "Missouri Employers Mutual",
    "Nationwide Mutual Insurance Company",
    "New York State Insurance Fund",
    "The Norfolk & Dedham Group",
    "Penn National Insurance",
    "Puerto Rico State Insurance Fund",
    "Sentry Insurance",
    "Society Insurance",
    "State Farm Insurance",
    "State Compensation Insurance Fund",
    "United Heartland",
    "Zenith Insurance Group",
    "Accenture",
    "ACORD",
    "AEU",
    "AGCS",
    "Agency Network Exchange",
    "AIG",
    "Allianz",
    "Allied World",
    "Allstate",
    "American Family Insurance",
    "AmTrust",
    "AmWins",
    "Aon",
    "Applied Systems",
    "Applied Underwriters",
    "Arch Insurance",
    "Argo Group",
    "ARS",
    "Aspen",
    "Assurant",
    "AXA",
    "AXA XL",
    "AXIS Capital",
    "Beazley",
    "Berkley",
    "Berkshire Hathaway",
    "Brit",
    "Brown & Brown",
    "Brown & Riding",
    "Burns and Wilcox",
    "Canopius",
    "Century Insurance",
    "CFC Underwriting",
    "Charity First",
    "Chubb",
    "CNA",
    "Crawford & Company",
    "CTC Transportation",
    "DUAL",
    "EZLynx",
    "Farmers",
    "First Onsite Property Restoration",
    "FM Global",
    "Foremost Insurance Group",
    "Gallagher",
    "Gallagher Bassett",
    "GEICO",
    "General Star",
    "Generali",
    "Genworth",
    "Gorst & Compass",
    "Great American Insurance Group",
    "Guy Carpenter",
    "Hanover Insurance Group",
    "Hartford",
    "HCC Specialty",
    "HDI",
    "Hiscox",
    "Howden",
    "HUB International",
    "Hyperion Insurance Group",
    "InsurBanc",
    "Intact",
    "Ironshore",
    "ITC",
    "Kaufman",
    "Legal & General",
    "Lemonade",
    "Lexington",
    "Liberty International Underwriter",
    "Liberty Mutual",
    "Liberty Specialty Markets",
    "Lloyd's",
    "Lloyd's of London",
    "Lockton Companies",
    "Manulife",
    "Markel Corporation",
    "Marsh",
    "Marsh McLennan",
    "Marshberry",
    "Mercer",
    "Mercury Insurance",
    "MetLife",
    "MS Amlin",
    "Munich Re",
    "NAPLSO",
    "NAS Insurance",
    "Nationwide",
    "NIF Group",
    "Oak Street",
    "Old Republic",
    "Philadelphia Insurance",
    "Pioneer Underwriting",
    "Progressive Insurance",
    "Prudential Plc",
    "QBE",
    "RFIB",
    "Risk Placement Services",
    "RKH Specialty",
    "RT Specialty",
    "Ryan Specialty Group",
    "Safety National",
    "SCOR",
    "Sedgwick",
    "SIAA",
    "Smart Choice",
    "Sompo",
    "Starr Companies",
    "State Farm",
    "Summit",
    "Swiss Re",
    "Texas Mutual",
    "The Institutes",
    "Tokio Marine",
    "Travelers",
    "Trisura",
    "Worldwide Facilities",
    "WSIA",
    "WTW",
    "XL Catlin",
    "Zurich"
]

#print(len(semifinal_list_2))

# add_list = [ 'ACSTAR INSURANCE COMPANY', 'ALL AMERICA INSURANCE COMPANY', 'AMERICAN ALTERNATIVE INSURANCE CORPORATION', 'AMERICAN CONTRACTORS INDEMNITY COMPANY', 'AMERICAN ROAD INSURANCE COMPANY (THE)', 'ASPEN AMERICAN INSURANCE COMPANY', 
#             'BITCO GENERAL INSURANCE CORPORATION', 'BOND SAFEGUARD INSURANCE COMPANY', 'BRITISH AMERICAN INSURANCE COMPANY', 'CENTRAL MUTUAL INSURANCE COMPANY',       
#     'CENTURY SURETY COMPANY', 'CHUBB INDEMNITY INSURANCE COMPANY', 'CINCINNATI INDEMNITY COMPANY, THE', 'CITIZENS INSURANCE COMPANY OF AMERICA', 
#     'COLONIAL AMERICAN CASUALTY AND SURETY COMPANY', 'COLONIAL SURETY COMPANY', 'CONTINENTAL HERITAGE INSURANCE COMPANY', 
#     'CONTRACTORS BONDING AND INSURANCE COMPANY', 'CUMIS INSURANCE SOCIETY, INC.', 'FEDERATED MUTUAL INSURANCE COMPANY', 'FIDELITY AND GUARANTY INSURANCE COMPANY', 
#     'GENERAL STAR NATIONAL INSURANCE COMPANY', 'GRANITE RE, INC.', 'GRAY CASUALTY & SURETY COMPANY (THE)', 'GRAY INSURANCE COMPANY (THE)', 
#     'GREAT AMERICAN INSURANCE COMPANY OF NEW YORK',   
#     'HARCO NATIONAL INSURANCE COMPANY', 'IRONSHORE INDEMNITY INC.', 'ISLAND INSURANCE COMPANY, LIMITED', 'LEXINGTON NATIONAL INSURANCE CORPORATION', 
#     'MARKEL INSURANCE COMPANY', 'MID-CONTINENT CASUALTY COMPANY', 'NATIONAL FARMERS UNION PROPERTY AND CASUALTY COMPANY', 
#     'NATIONAL TRUST INSURANCE COMPANY', 'NAVIGATORS INSURANCE COMPANY', 'NEW YORK MARINE AND GENERAL INSURANCE COMPANY', 
#     'OLD DOMINION INSURANCE COMPANY', 'PARTNER REINSURANCE COMPANY OF THE U.S.', 
#     'PHILADELPHIA INDEMNITY INSURANCE COMPANY', 'PLATTE RIVER INSURANCE COMPANY', 'SERVICE INSURANCE COMPANY INC. (THE)', 'SIRIUSPOINT AMERICA INSURANCE COMPANY', 
#     'SOUTHWEST MARINE AND GENERAL INSURANCE COMPANY', 'ST. PAUL GUARDIAN INSURANCE COMPANY', 'SURETY BONDING COMPANY OF AMERICA', 'TRANSATLANTIC REINSURANCE COMPANY', 
#     'TRAVELERS INDEMNITY COMPANY OF AMERICA (THE)', 'UNITED CASUALTY AND SURETY INSURANCE COMPANY', 'UNITED FIRE & INDEMNITY COMPANY', 'UNITED SURETY AND INDEMNITY COMPANY', 
#     'UNIVERSAL INSURANCE COMPANY', 'UNIVERSAL UNDERWRITERS INSURANCE COMPANY', 'WEST BEND INSURANCE COMPANY'
#  ]


# print(len(additional_list))

names_sentence_case = [
    "ACE American Insurance Company",
    "ACE Property and Casualty Insurance Company",
    "ACSTAR INSURANCE COMPANY",
    "ACUITY",
    "ALL AMERICA INSURANCE COMPANY",
    "Allegheny Casualty Company",
    "ALLIED Property and Casualty Insurance Company",
    "Allied World Insurance Company",
    "Allied World Specialty Insurance Company",
    "AMCO Insurance Company",
    "AMERICAN ALTERNATIVE INSURANCE CORPORATION",
    "American Casualty Company of Reading, Pennsylvania",
    "AMERICAN CONTRACTORS INDEMNITY COMPANY",
    "American Fire and Casualty Company",
    "American Guarantee and Liability Insurance Company",
    "American Home Assurance Company",
    "AMERICAN ROAD INSURANCE COMPANY (THE)",
    "American Select Insurance Company",
    "American Southern Insurance Company",
    "American Surety Company",
    "Amerisure Insurance Company",
    "Amerisure Mutual Insurance Company",
    "Amerisure Partners Insurance Company",
    "Antilles Insurance Company",
    "Arch Insurance Company",
    "Arch Reinsurance Company",
    "Argonaut Insurance Company",
    "Ascot Surety & Casualty Company",
    "ASPEN AMERICAN INSURANCE COMPANY",
    "Atlantic Specialty Insurance Company",
    "Auto-Owners Insurance Company",
    "AXIS Insurance Company",
    "AXIS Reinsurance Company",
    "Bankers Insurance Company",
    "Bankers Standard Insurance Company",
    "Beazley Insurance Company, Inc.",
    "Berkley Insurance Company",
    "Berkley National Insurance Company",
    "Berkley Regional Insurance Company",
    "Berkshire Hathaway Homestate Insurance Company",
    "Berkshire Hathaway Specialty Insurance Company",
    "BITCO GENERAL INSURANCE CORPORATION",
    "BOND SAFEGUARD INSURANCE COMPANY",
    "Bondex Insurance Company",
    "Brierfield Insurance Company",
    "BRITISH AMERICAN INSURANCE COMPANY",
    "Capitol Indemnity Corporation",
    "Carolina Casualty Insurance Company",
    "Centennial Casualty Company",
    "CENTRAL MUTUAL INSURANCE COMPANY",
    "CENTURY SURETY COMPANY",
    "Charter Oak Fire Insurance Company (The)",
    "Cherokee Insurance Company",
    "CHUBB INDEMNITY INSURANCE COMPANY",
    "Cincinnati Casualty Company (The)",
    "CINCINNATI INDEMNITY COMPANY, THE",
    "Cincinnati Insurance Company (The)",
    "CITIZENS INSURANCE COMPANY OF AMERICA",
    "COLONIAL AMERICAN CASUALTY AND SURETY COMPANY",
    "COLONIAL SURETY COMPANY",
    "Continental Casualty Company",
    "CONTINENTAL HERITAGE INSURANCE COMPANY",
    "Continental Insurance Company (The)",
    "CONTRACTORS BONDING AND INSURANCE COMPANY",
    "Cooperativa de Seguros Multiples de Puerto Rico",
    "CorePointe Insurance Company",
    "Crestbrook Insurance Company",
    "CUMIS INSURANCE SOCIETY, INC.",
    "CUMIS Specialty Insurance Company, Inc.",
    "Developers Surety and Indemnity Company",
    "Employers Insurance Company of Wausau",
    "Employers Mutual Casualty Company",
    "Endurance American Insurance Company",
    "Endurance Assurance Corporation",
    "Erie Insurance Company",
    "Euler Hermes North America Insurance Company",
    "Everest National Insurance Company",
    "Everest Reinsurance Company",
    "Evergreen National Indemnity Company",
    "Executive Risk Indemnity Inc.",
    "Explorer Insurance Company",
    "Fair American Insurance and Reinsurance Company",
    "Farmers Alliance Mutual Insurance Company",
    "Farmington Casualty Company",
    "FCCI Insurance Company",
    "Federal Insurance Company",
    "FEDERATED MUTUAL INSURANCE COMPANY",
    "Fidelity and Deposit Company of Maryland",
    "FIDELITY AND GUARANTY INSURANCE COMPANY",
    "Fidelity and Guaranty Insurance Underwriters, Inc.",
    "Financial Casualty & Surety, Inc.",
    "Financial Pacific Insurance Company",
    "Fireman's Fund Insurance Company",
    "First Founders Assurance Company",
    "First Net Insurance Company",
    "Frankenmuth Insurance Company",
    "General Casualty Company Of Wisconsin",
    "General Reinsurance Corporation",
    "GENERAL STAR NATIONAL INSURANCE COMPANY",
    "GRANITE RE, INC.",
    "Granite State Insurance Company",
    "GRAY CASUALTY & SURETY COMPANY (THE)",
    "GRAY INSURANCE COMPANY (THE)",
    "Great American Alliance Insurance Company",
    "Great American Insurance Company",
    "GREAT AMERICAN INSURANCE COMPANY OF NEW YORK",
    "Great American Security Insurance Company",
    "Great Midwest Insurance Company",
    "Great Northern Insurance Company",
    "Guarantee Company of North America USA (The)",
    "Hanover Insurance Company (The)",
    "HARCO NATIONAL INSURANCE COMPANY",
    "Hartford Accident and Indemnity Company",
    "Hartford Casualty Insurance Company",
    "Hartford Fire Insurance Company",
    "Hartford Insurance Company of the Midwest",
    "HDI Global Select Insurance Company",
    "Hudson Insurance Company",
    "IMT Insurance Company",
    "Indemnity Insurance Company of North America",
    "Indemnity National Insurance Company",
    "Inland Insurance Company",
    "Insurance Company Of North America",
    "Insurance Company of the State of Pennsylvania (The)",
    "Insurance Company of the West",
    "Insurors Indemnity Company",
    "International Fidelity Insurance Company",
    "IRONSHORE INDEMNITY INC.",
    "ISLAND INSURANCE COMPANY, LIMITED",
    "LEXINGTON NATIONAL INSURANCE CORPORATION",
    "Lexon Insurance Company",
    "Liberty Mutual Fire Insurance Company",
    "Liberty Mutual Insurance Company",
    "LM Insurance Corporation",
    "Manufacturers Alliance Insurance Company",
    "MARKEL INSURANCE COMPANY",
    "Massachusetts Bay Insurance Company",
    "Merchants Bonding Company (Mutual)",
    "Merchants National Bonding, Inc.",
    "Michigan Millers Mutual Insurance Company",
    "Mid-Century Insurance Company",
    "MID-CONTINENT CASUALTY COMPANY",
    "Motorists Mutual Insurance Company",
    "Motors Insurance Corporation",
    "Munich Reinsurance America, Inc.",
    "National American Insurance Company",
    "National Casualty Company",
    "NATIONAL FARMERS UNION PROPERTY AND CASUALTY COMPANY",
    "National Fire & Marine Insurance Company",
    "National Fire Insurance Company of Hartford",
    "National Indemnity Company",
    "National Liability & Fire Insurance Company",
    "NATIONAL TRUST INSURANCE COMPANY",
    "National Union Fire Insurance Company of Pittsburgh, PA",
    "Nationwide Agribusiness Insurance Company",
    "Nationwide Mutual Insurance Company",
    "NAVIGATORS INSURANCE COMPANY",
    "New Hampshire Insurance Company",
    "NEW YORK MARINE AND GENERAL INSURANCE COMPANY",
    "NGM Insurance Company",
    "NOVA Casualty Company",
    "Ohio Casualty Insurance Company (The)",
    "Ohio Farmers Insurance Company",
    "Ohio Indemnity Company",
    "Oklahoma Surety Company",
    "OLD DOMINION INSURANCE COMPANY",
    "Old Republic General Insurance Corporation",
    "Old Republic Insurance Company",
    "Old Republic Surety Company",
    "Pacific Indemnity Company",
    "PARTNER REINSURANCE COMPANY OF THE U.S.",
    "Pekin Insurance Company",
    "Pennsylvania Insurance Company",
    "Pennsylvania Manufacturers' Association Insurance Company",
    "Pennsylvania Manufacturers Indemnity Company",
    "Pennsylvania National Mutual Casualty Insurance Company",
    "PHILADELPHIA INDEMNITY INSURANCE COMPANY",
    "PLATTE RIVER INSURANCE COMPANY",
    "Plaza Insurance Company",
    "ProCentury Insurance Company",
    "Progressive Casualty Insurance Company",
    "Progressive Northwestern Insurance Company",
    "Protective Insurance Company",
    "Protective Property & Casualty Insurance Company",
    "QBE Insurance Corporation",
    "Regent Insurance Company",
    "RLI Insurance Company",
    "Roche Surety and Casualty Company, Inc.",
    "Rockwood Casualty Insurance Company",
    "SAFECO Insurance Company of America",
    "Safety National Casualty Corporation",
    "Sagamore Insurance Company",
    "SECURA Insurance Company",
    "Selective Insurance Company of America",
    "Seneca Insurance Company, Inc.",
    "Sentry Insurance Company",
    "Sentry Select Insurance Company",
    "SERVICE INSURANCE COMPANY INC. (THE)",
    "SIRIUSPOINT AMERICA INSURANCE COMPANY",
    "SOUTHWEST MARINE AND GENERAL INSURANCE COMPANY",
    "St. Paul Fire and Marine Insurance Company",
    "ST. PAUL GUARDIAN INSURANCE COMPANY",
    "St. Paul Mercury Insurance Company",
    "Standard Fire Insurance Company (The)",
    "Star Insurance Company",
    "StarNet Insurance Company",
    "Starr Specialty Insurance Company",
    "State Auto Property and Casualty Insurance Company",
    "State Automobile Mutual Insurance Company",
    "State Farm Fire and Casualty Company",
    "Stillwater Property and Casualty Insurance Company",
    "SureTec Insurance Company",
    "SURETY BONDING COMPANY OF AMERICA",
    "Swiss Re Corporate Solutions America Insurance Corporation",
    "Swiss Re Corporate Solutions Premier Insurance Corporation",
    "Swiss Reinsurance America Corporation",
    "TRANSATLANTIC REINSURANCE COMPANY",
    "Travelers Casualty and Surety Company",
    "Travelers Casualty and Surety Company of America",
    "Travelers Casualty Insurance Company of America",
    "Travelers Indemnity Company (The)",
    "TRAVELERS INDEMNITY COMPANY OF AMERICA (THE)",
    "Travelers Indemnity Company of Connecticut (The)",
    "Travelers Property Casualty Company of America",
    "U.S. Specialty Insurance Company",
    "Union Insurance Company",
    "UNITED CASUALTY AND SURETY INSURANCE COMPANY",
    "United Fire & Casualty Company",
    "UNITED FIRE & INDEMNITY COMPANY",
    "United States Fidelity and Guaranty Company",
    "United States Fire Insurance Company",
    "United States Surety Company",
    "UNITED SURETY AND INDEMNITY COMPANY",
    "Universal Fire & Casualty Insurance Company",
    "UNIVERSAL INSURANCE COMPANY",
    "Universal Surety Company",
    "UNIVERSAL UNDERWRITERS INSURANCE COMPANY",
    "Utica Mutual Insurance Company",
    "VerTerra Insurance Company",
    "Vigilant Insurance Company",
    "West American Insurance Company",
    "WEST BEND INSURANCE COMPANY",
    "Westchester Fire Insurance Company",
    "Western National Mutual Insurance Company",
    "Western Surety Company",
    "Westfield Insurance Company",
    "Westfield National Insurance Company",
    "Westport Insurance Corporation",
    "XL Specialty Insurance Company",
    "Zurich American Insurance Company"
]

web_list = [name.title() for name in names_sentence_case]
# print(names_sentence_case)

# print(len(web_list))

combined_list = semifinal_list + semifinal_list_2 + web_list 

# print(combined_list)

# fi_list = ['CNA Surety', 'American Modern Insurance Group', 'New Heights Insurance Solutions', 'NEW MEXICO FAIR PLAN', 'Redpoint County Mutual Company', 'AmTrust Financial Services, Inc.', 'CRC Group Wholesale & Specialty', 'Lemonade Insurance', 'Burns & Wilcox', 'Kinsale Insurance', 'Employers Insurance Company of Nevada', 'Risk Exchange Insurance Services, Inc.', 'MetLife', 'Centene Corporation', 'Kelly Klee', 'Chesapeake Employers Insurance', 'GIG Insurance Group', 'Smart Choice Agents', 'Insential Inc.', 'AIG (American International Group)', 'Crum & Forster Specialty Insurance Company', 'Mesa Underwriters Specialty Insurance', 'Risk Placement Service', 'Clearcover Insurance Company', 'PROPELLER BONDS', 
#  'All Risks Limited', 'MetLife Auto & Home®', 'One Beacon', 'US Assure', 'TAPCO Underwriters Inc.', 'Cincinnati Insurance', 'Breckenridge Insurance Services', 'Liberty Mutual', 'RLI Insurance Company', 'Virtus Insurance', 'Wright National Flood Insurance Company', 'Pathpoint', 'Lincoln Financial Group', 'Kaiser Permanente', 'Kemper', 'AmGUARD', 'Philadelphia Insurance Company', 'Principal Financial Group', 'Arch Insurance Company', 'Encompass Insurance', 'Molina Healthcare', 
# 'Transamerica', 'Insurance Solutions Group', 'Colonial Surety Company', 'International Excess', 'Thimble Insurance Services', 'Safeco Insurance', 'Berkshire Hathaway (GUARD Insurance Companies)', 'Berkley Asset Protection', 'Bass Underwriters', 'CNA Insurance', 'Mercer Insurance Group', 'GEICO', 'Arthur J. Gallagher', 'Berkley Regional Specialty Insurance Company', 'RLI Surety', 'State Auto Insurance', 'Mercury Insurance', 'FIRST CONNECT', 'Zurich', 'John Hancock', 'California Earthquake Authority (CEA)', 'Markel Insurance Company', 'National Fire Insurance of Hartford', 'Berkshire Hathaway Inc.', 'Beazley', 'New York Life', 'SELECTIVE INSURANCE GROUP INC.', 'NEXT Insurance', 'QBE Insurance Corporation', 'National Program Administrators', 'Foremost', 'American National Insurance', 'Stillwater Insurance Services, Inc.', 'USLI', 'Anthem', "Kentucky Employers' Mutual Insurance", 'Assurant', 'Western Pacific Insurance Network, Inc.', 'Ohio Casualty', 'NFP Property & Casualty Services, Inc.', 'ECC Insurance Brokers, LLC', 'TransGuard Insurance Company of America, Inc.', 'State Farm', 'Northwestern Mutual', 'NETWORKED | AMWINS DAIS', 'First American', 'Hiscox', 'Union Standard Insurance Group', 'MassMutual', 'Aetna', 'Mountain States Mutual Casualty Company', 'Auto-Owners Insurance', 'Topa Insurance Company', 'CID Insurance Programs', 'Everguard Insurance', 'Irwin Siegel Agency, Inc.', 'AmWINS Access Insurance', 'Blue Cross Blue Shield', 'USAA', 'Preferred Employers Insurance Company', 'Starstone National Insurance', 'Front Row Insurance', 'Amica Mutual Insurance', 'Southwest Insurance Group', 'PURE Insurance', 'IIAA Agency Administrative Services, Inc.', 'Western Pacific Mutual Insurance Company', 'Zurich North America', 'Allstate', 'Ryan Turner Specialty', 'CannGen Insurance Services', 'Foremost Insurance Group', 'Chubb', 'Texas Mutual', 'Penn National Insurance', 'American Modern Insurance', 'American Family Insurance', 'Nationwide', 'PIE Insurance', 'UnitedHealthcare', 'Health Care Service Corporation (HCSC)', 'Surety Placement Services, LLC', 'Infinity Insurance', 'Neptune', 'Apogee Insurance Group', 'Travelers Texas MGA', 'Farmers Insurance', 'FISIF-Food Industry Self-Insurance Fund', 'Bold Penguin', 'COVER Financial', 'HBW (Hull & Company)', 'Mercury County Mutual - TX', 'Markel Corporation', 'AmWINS Brokerage', 'Nationwide Insurance', 'Erie Insurance', 'IBIS-Independent Bankers Insurance Services', 'Attune', 'Wright Flood', 'Cowbell Insurance', 'AIG', 'Privilege Underwriters Reciprocal Exchange (PURE)', 'Sentry Insurance', 'Travelers', 'ASI (American Strategic Insurance)', 'PEACHTREE SPECIAL RISK BROKERS, LLC', 'Orchid', 'Prudential Financial', 'Humana', 'SPECIAL MARKETS INSURANCE CONSULTANTS', 'The Hartford', 'Hartford', 'Specialty Market Insurance Consultants, Inc.', 'Donegal', 'Guardian Life', 'Progressive', 'Progressive Insurance', 'New Mexico Mutual Casualty Company', 'Cigna', '21st Century Insurance', 'Acuity Insurance', 'Aflac', 'Allianz Life', 'Allied Insurance', 'Allstate', 'American Automobile Association (AAA)', 
# 'American Family Insurance', 'American Income Life Insurance Company', 'American International Group (AIG)', 'American National Insurance Company', 'American Strategic Insurance (ASI)', 'Ameriprise Auto & Home Insurance', 'Ameriprise Financial', 'Ameritas Life Insurance Company', 'Amica Mutual Insurance', 'Amtrust Financial Services', 'Applied Underwriters', 'Arbella Insurance Group', 'Assurant', 'Assurity Life Insurance Company', 'Auto-Owners Insurance', 'AXA Equitable Life Insurance Company', 'Bankers Life and Casualty Company', 'Berkshire Hathaway', 'Brotherhood Mutual Insurance Company', 'CareSource', 'Chubb Corp', 'Citizens Property Insurance Corporation', 'CNA Financial', 'CNO Financial Group', 'Colonial Life & Accident Insurance Company', 'Combined Insurance', 'Commerce Insurance Group', 'Country Financial', 'Delta Dental', 'Encompass Insurance Company', 'Erie Insurance Group', 'Esurance', 'Evergreen USA RRG', 'Farmers Insurance Group', 'Federated Mutual Insurance Company', 'First Insurance Company of Hawaii', 'FM Global', 'Fortegra Group', 'GAINSCO', 'GEICO', 'General Re', 'Genworth Financial', 'Gerber Life Insurance Company', 'Globe Life And Accident Insurance Company', 'GMAC Insurance', 'Gracy Title Company', 'Grange Mutual Casualty Company', 'The Guardian Life Insurance Company of America', 'GuideOne Insurance', 'Hagerty Insurance Agency', 'Hanover Insurance', 'The Hartford', 'HCC Insurance Holdings', 'Hiscox Small Business Insurance', 'Horace Mann Educators Corporation', 'Ironshore', 'K&K Insurance', 'Kansas City Life Insurance Company', 'Kemper Corporation', 'Knights of Columbus', 'Lemonade (insurance)', 'Liberty Mutual', 'Lincoln National Corporation', 'Manhattan Life Insurance Company', 'Markel Corporation', 'MassMutual', 'Merchants Insurance Group', 'Mercury Insurance Group', 'MetLife', 'Metromile', 'Modern Woodmen of America', 'Mutual of Omaha', 'National Flood Insurance Program', 'Nationwide Mutual Insurance Company', 'New Jersey Manufacturers Insurance Company', 'New York Life Insurance Company', 'NJM Insurance Group', 'The Norfolk & Dedham Group', 'Northwestern Mutual', 'Omega', 'Oxford Health Plans', 'Pacific Life', 'PEMCO', 'Penn Mutual', 'Penn National Insurance', 'Philadelphia Contributionship for the Insurance of Houses from Loss by Fire', 'Philadelphia Insurance Companies', 'Physicians Mutual', 'Primerica', 'Principal Financial Group', 'Progressive', 'ProSight Specialty Insurance', 'Protective Life', 'Prudential Financial', 'Pure Insurance', 'QBE', 'The Regence Group', 'Reliance Insurance Company', 'Reliance Partners', 'RLI Corp.', 'Safe Auto Insurance Company', 'Safeco', 'Safeway Insurance Group', 'Securian Financial Group', 'Sentry Insurance', 'Shelter Insurance', 'Society Insurance', 'Southern Aid and Insurance Company', 'SquareTrade', 'Standard Insurance Company', 'State Automobile Mutual Insurance Company', 'State Farm Insurance', 'Sun Life Financial', 'Symetra', 'The General', 'The Travelers Companies', 'TIAA', 'Titan Insurance Company', 'Transamerica Corporation', 'Tricare', 'Trupanion', 
# 'UPC Insurance', 'Unum', 'USAA', 'West Coast Life', 'Western & Southern Financial Group', 'Western Mutual Insurance Group', 'Westfield Insurance', 'White Mountains Insurance Group', 'W. R. Berkley Corporation', 'XL Catlin', 
# 'Zurich Insurance Group', 'Aflac', 'Allianz Life', 'Allstate', 'American Family Insurance', 'American Fidelity Assurance', 'American Income Life Insurance Company', 'Ameritas Life Insurance Company', 'Amica Mutual Insurance', 'Assurity Life Insurance Company', 'AXA Equitable Life Insurance Company', 'Bankers Life and Casualty', 'Banner Life Insurance Company', 'Colonial Life & Accident Insurance Company', 'Colonial Penn', 'Conseco', 'Farmers Insurance Group', 'Garden State Life', 'Genworth Financial', 'The Great-West Life Assurance Company', 'Gerber Life Insurance Company', 'Globe Life And Accident Insurance Company', 'The Guardian Life Insurance Company of America', 'Horace Mann Educators Corporation', 'ING Group', 'Jackson National Life', 'John Hancock Life Insurance', 'Kansas City Life Insurance Company', 'Lincoln National Corporation', 'Manhattan Life Insurance Company', 'MEGA Life and Health Insurance', 'MetLife', 'Mutual of Omaha', 'National Life Group', 'National Western Life Insurance Company', 'Nationwide Mutual Insurance Company', 'New York Life Insurance Company', 'Ohio National Financial Services Company', 'Pacific Life', 'Physicians Mutual', 'Primerica', 'Protective Life', 'Prudential Financial', 'Securian Financial Group', 'Standard Insurance Company', 'State Farm Insurance', 'Thrivent', 'TIAA-CREF', 'Transamerica Corporation', 'UNIFI Companies', 'United of Omaha', 'Western & Southern Financial Group', 
# 'AARP', 'Aetna', 'American National Insurance Company', 'Amerigroup', 'Blue Cross and Blue Shield Association', 'Bright Health', 'CareSource', 'Cambia Health Solutions', 'Centene Corporation', 'Cigna', 'Compass Rose Benefits Group', 'Delta Dental', 'Elevance Health', 'EmblemHealth', 'Fallon Health', 'Geisinger', 'Golden Rule Insurance Company', 'Harvard Pilgrim Health Care', 'Health Net', 'HealthMarkets', 'HealthPartners', 'Highmark', 'Humana', 'Independence Blue Cross', 'Kaiser Permanente', 'Kaleida Health', 'MassHealth', 'Medical Mutual of Ohio', 'Molina Healthcare', 'Oscar Health', 'Oxford Health Plans', 'Premera Blue Cross', 'Principal Financial Group', 'Shelter Insurance', 'State Farm', 
# 'Thrivent Financial for Lutherans', 'UnitedHealth Group', 'Unitrin', 'WellCare', 'Aetna', 'American Family Insurance', 'Bankers Life and Casualty', 'CareSource', 'Conseco', 'Fidelis Care', 'Kaiser Permanente', 'Mutual of Omaha', 'Physicians Mutual', 'Premera Blue Cross', 'Thrivent Financial for Lutherans', 'United American Insurance Company', 'Accident Fund Insurance Company of America', 'American International Group (AIG)', 'AmTrust Financial Services', 'Cincinnati Financial Corporation', 'Erie Insurance Group', 'GUARD Insurance Group', 'Hanover Insurance', 'The Hartford', 'Liberty Mutual', 'Merchants Insurance Group', 'Missouri Employers Mutual', 'Nationwide Mutual Insurance Company', 'New York State Insurance Fund', 'The Norfolk & Dedham Group', 'Penn National Insurance', 'Puerto Rico State Insurance Fund', 'Sentry Insurance', 'Society Insurance', 'State Farm Insurance', 'State Compensation Insurance Fund', 'United Heartland', 'Zenith Insurance Group', 'Accenture', 'ACORD', 'AEU', 'AGCS', 'Agency Network Exchange', 'AIG', 'Allianz', 'Allied World', 'Allstate', 'American Family Insurance', 'AmTrust', 'AmWins', 'Aon', 'Applied Systems', 'Applied Underwriters', 'Arch Insurance', 'Argo Group', 'ARS', 'Aspen', 'Assurant', 'AXA', 'AXA XL', 'AXIS Capital', 'Beazley', 'Berkley', 'Berkshire Hathaway', 'Brit', 'Brown & Brown', 'Brown & Riding', 'Burns and Wilcox', 'Canopius', 'Century Insurance', 'CFC Underwriting', 'Charity First', 'Chubb', 'CNA', 'Crawford & Company', 'CTC Transportation', 'DUAL', 'EZLynx', 'Farmers', 'First Onsite Property Restoration', 'FM Global', 'Foremost Insurance Group', 'Gallagher', 'Gallagher Bassett', 'GEICO', 
# 'General Star', 'Generali', 'Genworth', 'Gorst & Compass', 'Great American Insurance Group', 'Guy Carpenter', 'Hanover Insurance Group', 'Hartford', 'HCC Specialty', 'HDI', 'Hiscox', 'Howden', 'HUB International', 'Hyperion Insurance Group', 'InsurBanc', 'Intact', 'Ironshore', 'ITC', 'Kaufman', 'Legal & General', 'Lemonade', 'Lexington', 'Liberty International Underwriter', 'Liberty Mutual', 'Liberty Specialty Markets', "Lloyd's", "Lloyd's of London", 'Lockton Companies', 'Manulife', 'Markel Corporation', 'Marsh', 'Marsh McLennan', 'Marshberry', 'Mercer', 'Mercury Insurance', 'MetLife', 'MS Amlin', 'Munich Re', 'NAPLSO', 'NAS Insurance', 'Nationwide', 'NIF Group', 'Oak Street', 'Old Republic', 'Philadelphia Insurance', 'Pioneer Underwriting', 'Progressive Insurance', 'Prudential Plc', 'QBE', 'RFIB', 'Risk Placement Services', 'RKH Specialty', 'RT Specialty', 'Ryan Specialty Group', 'Safety National', 'SCOR', 'Sedgwick', 'SIAA', 'Smart Choice', 'Sompo', 'Starr Companies', 'State Farm', 'Summit', 'Swiss Re', 'Texas Mutual', 'The Institutes', 'Tokio Marine', 'Travelers', 'Trisura', 'Worldwide Facilities', 'WSIA', 'WTW', 'XL Catlin', 'Zurich', 'Ace American Insurance Company', 'Ace Property And Casualty Insurance Company', 'Acstar Insurance Company', 'Acuity', 'All America Insurance Company', 'Allegheny Casualty Company', 'Allied Property And Casualty Insurance Company', 'Allied World Insurance Company', 'Allied World Specialty Insurance Company', 'Amco Insurance Company', 'American Alternative Insurance Corporation', 'American Casualty Company Of Reading, Pennsylvania', 'American Contractors Indemnity Company', 'American Fire And Casualty Company', 'American Guarantee And Liability Insurance Company', 'American Home Assurance Company', 'American Road Insurance Company (The)', 'American Select Insurance Company', 'American Southern Insurance Company', 'American Surety Company', 'Amerisure Insurance Company', 'Amerisure Mutual Insurance Company', 'Amerisure Partners Insurance Company', 'Antilles Insurance Company', 'Arch Insurance Company', 'Arch Reinsurance Company', 'Argonaut Insurance Company', 'Ascot Surety & Casualty Company', 'Aspen American Insurance Company', 'Atlantic Specialty Insurance Company', 'Auto-Owners Insurance Company', 'Axis Insurance Company', 'Axis Reinsurance Company', 'Bankers Insurance Company', 'Bankers Standard Insurance Company', 'Beazley Insurance Company, Inc.', 'Berkley Insurance Company', 'Berkley National Insurance Company', 'Berkley Regional Insurance Company', 'Berkshire Hathaway Homestate Insurance Company', 'Berkshire Hathaway Specialty Insurance Company', 'Bitco General Insurance Corporation', 'Bond Safeguard Insurance Company', 'Bondex Insurance Company', 'Brierfield Insurance Company', 'British American Insurance Company', 'Capitol Indemnity Corporation', 'Carolina Casualty Insurance Company', 'Centennial Casualty Company', 'Central Mutual Insurance Company', 'Century Surety Company', 'Charter Oak Fire Insurance Company (The)', 'Cherokee Insurance Company', 'Chubb Indemnity Insurance Company', 'Cincinnati Casualty Company (The)', 'Cincinnati Indemnity Company, The', 'Cincinnati Insurance Company (The)', 'Citizens Insurance Company Of America', 'Colonial American Casualty And Surety Company', 'Colonial Surety Company', 'Continental Casualty Company', 'Continental Heritage Insurance Company', 'Continental Insurance Company (The)', 'Contractors Bonding And Insurance Company', 'Cooperativa De Seguros Multiples De Puerto Rico', 'Corepointe Insurance Company', 'Crestbrook Insurance Company', 'Cumis Insurance Society, Inc.', 'Cumis Specialty Insurance Company, Inc.', 'Developers Surety And Indemnity Company', 'Employers Insurance Company Of Wausau', 'Employers Mutual Casualty Company', 'Endurance American Insurance Company', 'Endurance Assurance Corporation', 'Erie Insurance Company', 'Euler Hermes North America Insurance Company', 'Everest National Insurance Company', 'Everest Reinsurance Company', 'Evergreen National Indemnity Company', 'Executive Risk Indemnity Inc.', 'Explorer Insurance Company', 'Fair American Insurance And Reinsurance Company', 'Farmers Alliance Mutual Insurance Company', 'Farmington Casualty Company', 'Fcci Insurance Company', 'Federal Insurance Company', 'Federated Mutual Insurance Company', 'Fidelity And Deposit Company Of Maryland', 'Fidelity And Guaranty Insurance Company', 'Fidelity And Guaranty Insurance Underwriters, Inc.', 'Financial Casualty & Surety, Inc.', 'Financial Pacific Insurance Company', "Fireman'S Fund Insurance Company", 'First Founders Assurance Company', 'First Net Insurance Company', 'Frankenmuth Insurance Company', 'General Casualty Company Of Wisconsin', 'General Reinsurance Corporation', 'General Star National Insurance Company', 'Granite Re, Inc.', 'Granite State Insurance Company', 'Gray Casualty & Surety Company (The)', 'Gray Insurance Company (The)', 'Great American Alliance Insurance Company', 'Great American Insurance Company', 'Great American Insurance Company Of New York', 'Great American Security Insurance Company', 'Great Midwest Insurance Company', 'Great Northern Insurance Company', 'Guarantee Company Of North America Usa (The)', 'Hanover Insurance Company (The)', 'Harco National Insurance Company', 'Hartford Accident And Indemnity Company', 'Hartford Casualty Insurance Company', 'Hartford Fire Insurance Company', 'Hartford Insurance Company Of The Midwest', 'Hdi Global Select Insurance Company', 'Hudson Insurance Company', 'Imt Insurance Company', 'Indemnity Insurance Company Of North America', 'Indemnity National Insurance Company', 'Inland Insurance Company', 'Insurance Company Of North America', 'Insurance Company Of The State Of Pennsylvania (The)', 'Insurance Company Of The West', 'Insurors Indemnity Company', 'International Fidelity Insurance Company', 'Ironshore Indemnity Inc.', 'Island Insurance Company, Limited', 
# 'Lexington National Insurance Corporation', 'Lexon Insurance Company', 'Liberty Mutual Fire Insurance Company', 'Liberty Mutual Insurance Company', 'Lm Insurance Corporation', 'Manufacturers Alliance Insurance Company', 'Markel Insurance Company', 
# 'Massachusetts Bay Insurance Company', 'Merchants Bonding Company (Mutual)', 'Merchants National Bonding, Inc.', 'Michigan Millers Mutual Insurance Company', 'Mid-Century Insurance Company', 'Mid-Continent Casualty Company', 'Motorists Mutual Insurance Company', 'Motors Insurance Corporation', 'Munich Reinsurance America, Inc.', 'National American Insurance Company', 'National Casualty Company', 'National Farmers Union Property And Casualty Company', 'National Fire & Marine Insurance Company', 'National Fire Insurance Company Of Hartford', 'National Indemnity Company', 'National Liability & Fire Insurance Company', 'National Trust Insurance Company', 'National Union Fire Insurance Company Of Pittsburgh, Pa', 'Nationwide Agribusiness Insurance Company', 'Nationwide Mutual Insurance Company', 'Navigators Insurance Company', 'New Hampshire Insurance Company', 'New York Marine And General Insurance Company', 'Ngm Insurance Company', 'Nova Casualty Company', 'Ohio Casualty Insurance Company (The)', 'Ohio Farmers Insurance Company', 'Ohio Indemnity Company', 'Oklahoma Surety Company', 'Old Dominion Insurance Company', 'Old Republic General Insurance Corporation', 'Old Republic Insurance Company', 'Old Republic Surety Company', 'Pacific Indemnity Company', 'Partner Reinsurance Company Of The U.S.', 'Pekin Insurance Company', 'Pennsylvania Insurance Company', "Pennsylvania Manufacturers' Association Insurance Company", 'Pennsylvania Manufacturers Indemnity Company', 'Pennsylvania National Mutual Casualty Insurance Company', 'Philadelphia Indemnity Insurance Company', 'Platte River Insurance Company', 'Plaza Insurance Company', 
# 'Procentury Insurance Company', 'Progressive Casualty Insurance Company', 'Progressive Northwestern Insurance Company', 'Protective Insurance Company', 'Protective Property & Casualty Insurance Company', 'Qbe Insurance Corporation', 'Regent Insurance Company', 'Rli Insurance Company', 'Roche Surety And Casualty Company, Inc.', 'Rockwood Casualty Insurance Company', 'Safeco Insurance Company Of America', 'Safety National Casualty Corporation', 'Sagamore Insurance Company', 'Secura Insurance Company', 'Selective Insurance Company Of America', 'Seneca Insurance Company, Inc.', 'Sentry Insurance Company', 'Sentry Select Insurance Company', 'Service Insurance Company Inc. (The)', 'Siriuspoint America Insurance Company', 'Southwest Marine And General Insurance Company', 'St. Paul Fire And Marine Insurance Company', 'St. Paul Guardian Insurance Company', 'St. Paul Mercury Insurance Company', 'Standard Fire Insurance Company (The)', 'Star Insurance Company', 'Starnet Insurance Company', 'Starr Specialty Insurance Company', 'State Auto Property And Casualty Insurance Company', 'State Automobile Mutual Insurance Company', 'State Farm Fire And Casualty Company', 'Stillwater Property And Casualty Insurance Company', 'Suretec Insurance Company', 'Surety Bonding Company Of America', 'Swiss Re Corporate Solutions America Insurance Corporation', 'Swiss Re Corporate Solutions Premier Insurance Corporation', 'Swiss Reinsurance America Corporation', 'Transatlantic Reinsurance Company', 'Travelers Casualty And Surety Company', 'Travelers Casualty And Surety Company Of America', 'Travelers Casualty Insurance Company Of America', 'Travelers Indemnity Company (The)', 'Travelers Indemnity Company Of America (The)', 'Travelers Indemnity Company Of Connecticut (The)', 'Travelers Property Casualty Company Of America', 'U.S. Specialty Insurance Company', 'Union Insurance Company', 'United Casualty And Surety Insurance Company', 'United Fire & Casualty Company', 'United Fire & Indemnity Company', 'United States Fidelity And Guaranty Company', 'United States Fire Insurance Company', 'United States Surety Company', 'United Surety And Indemnity Company', 'Universal Fire & Casualty Insurance Company', 'Universal Insurance Company', 'Universal Surety Company', 'Universal Underwriters Insurance Company', 'Utica Mutual Insurance Company', 'Verterra Insurance Company', 'Vigilant Insurance Company', 'West American Insurance Company', 'West Bend Insurance Company', 'Westchester Fire Insurance Company', 'Western National Mutual Insurance Company', 'Western Surety Company', 'Westfield Insurance Company', 'Westfield National Insurance Company', 'Westport Insurance Corporation', 'Xl Specialty Insurance Company', 'Zurich American Insurance Company'
# ]

# print(list(set(fi_list)))

final_list = ['Grange Mutual Casualty Company', 'Everest National Insurance Company', 'Bondex Insurance Company', 'AmTrust', 'Globe Life And Accident Insurance Company', 'Lemonade', 'Merchants Bonding Company (Mutual)', 'Ace Property And Casualty Insurance Company', 'AIG', 'NETWORKED | AMWINS DAIS', 'Country Financial', 'Old Dominion Insurance Company', 'Prudential Plc', 'National Trust Insurance Company', 'Ohio National Financial Services Company', 'AARP', 'Secura Insurance Company', 'Oscar Health', 'Indemnity Insurance Company Of North America', 'Sun Life Financial', 'American Southern Insurance Company', 'IIAA Agency Administrative Services, Inc.', 'American Modern Insurance', 'American Select Insurance Company', 'The Great-West Life Assurance Company', 'US Assure', 'Cooperativa De Seguros Multiples De Puerto Rico', 'Universal Surety Company', 'Insential Inc.', 'Sompo', 'United States Surety Company', 'Lm Insurance Corporation', 'Pekin Insurance Company', 'Southwest Marine And General Insurance Company', 'Everguard Insurance', 'Kaleida Health', 'Preferred Employers Insurance Company', 'Lemonade (insurance)', 'AIG (American International Group)', 'Genworth Financial', 
              'Berkley Regional Insurance Company', 'Chubb Indemnity Insurance Company', 'Reliance Insurance Company', 'Risk Exchange Insurance Services, Inc.', 'Old Republic Surety Company', '21st Century Insurance', 'Argonaut Insurance Company', 'Sentry Select Insurance Company', 'American National Insurance', 'United Surety And Indemnity Company', 'Mutual of Omaha', 'Elevance Health', 'Marsh', 'Cincinnati Casualty Company (The)', 'Starr Companies', 'Nova Casualty Company', 'White Mountains Insurance Group', 'EZLynx', 'Insurors Indemnity Company', 'John Hancock', 'Employers Insurance Company Of Wausau', 'Progressive Insurance', 'Primerica', 'Philadelphia Insurance', 'Pennsylvania National Mutual Casualty Insurance Company', 'Travelers Indemnity Company Of America (The)', 'IBIS-Independent Bankers Insurance Services', 'American Alternative Insurance Corporation', 'New Mexico Mutual Casualty Company', 'Hanover Insurance Group', 'Golden Rule Insurance Company', 'TAPCO Underwriters Inc.', 'Sentry Insurance', 'Safeco Insurance Company Of America', 'Travelers Casualty And Surety Company Of America', 'USAA', 'Western National Mutual Insurance Company', 'Kaufman', 'Island Insurance Company, Limited', 'Amtrust Financial Services', 'Philadelphia Insurance Companies', 'Foremost', 'Gracy Title Company', 'Titan Insurance Company', 'Safeway Insurance Group', 'United Fire & Casualty Company', 'Central Mutual Insurance Company', 'Regent Insurance Company', 'Farmers Insurance', 'CRC Group Wholesale & Specialty', 'Erie Insurance Company', 'Ace American Insurance Company', 'Western & Southern Financial Group', 'Jackson National Life', 'International Fidelity Insurance Company', 'Pioneer Underwriting', 'Westfield National Insurance Company', 'The Hartford', 'Knights of Columbus', 'Hiscox Small Business Insurance', 'Hartford Insurance Company Of The Midwest', 'Pennsylvania Insurance Company', 
              'Cincinnati Insurance Company (The)', 'Axis Insurance Company', 'Liberty Mutual Insurance Company', 'Stillwater Property And Casualty Insurance Company', 'National Liability & Fire Insurance Company', 'RLI Corp.', 'Westfield Insurance', 'Ohio Casualty', 'Guy Carpenter', 'Berkshire Hathaway Homestate Insurance Company', 'Marsh McLennan', 'Northwestern Mutual', 'Thrivent', "Fireman'S Fund Insurance Company", 'Nationwide Mutual Insurance Company', 'Nationwide Insurance', 'United Heartland', 'Explorer Insurance Company', 'Universal Fire & Casualty Insurance Company', 'Fortegra Group', 'Kelly Klee', 'National Farmers Union Property And Casualty Company', 'Century Surety Company', 'Great Northern Insurance Company', 'All America Insurance Company', 'Amerisure Insurance Company', 'Virtus Insurance', 'United States Fidelity And Guaranty Company', 'Insurance Solutions Group', 'Gerber Life Insurance Company', 'United Fire & Indemnity Company', 
              'Crestbrook Insurance Company', 'The General', 'Liberty International Underwriter', 'Bankers Insurance Company', 'Platte River Insurance Company', 'Swiss Re Corporate Solutions America Insurance Corporation', 'Standard Insurance Company', 'TIAA-CREF', 'Amerisure Partners Insurance Company', 'Insurance Company Of The State Of Pennsylvania (The)', 'HUB International', 'Corepointe Insurance Company', 'Cowbell Insurance', 'Topa Insurance Company', 'Travelers Casualty And Surety Company', 'Farmers', 'Manhattan Life Insurance Company', 'Harco National Insurance Company', 'Mercury Insurance Group', 'CNA Financial', 'Swiss Re Corporate Solutions Premier Insurance Corporation', 'Brotherhood Mutual Insurance Company', 'Starr Specialty Insurance Company', 'Travelers Indemnity Company Of Connecticut (The)', "Pennsylvania Manufacturers' Association Insurance Company", 'Anthem', 'Sagamore Insurance Company', 'New York Marine And General Insurance Company', 'Old Republic General Insurance Corporation', 'Plaza Insurance Company', 'CareSource', 'Allstate', 'Universal Underwriters Insurance Company', 'Western Mutual Insurance Group', 'National Western Life Insurance Company', 'CNO Financial Group', 'Euler Hermes North America Insurance Company', 'Hartford Casualty Insurance Company', 'Shelter Insurance', 'Symetra', 'Markel Corporation', 'Safe Auto Insurance Company', 'Citizens Insurance Company Of America', 
              'Employers Insurance Company of Nevada', 'West Coast Life', 'Union Standard Insurance Group', 'Colonial Surety Company', 'Amerigroup', 'ACORD', 'TransGuard Insurance Company of America, Inc.', 'Old Republic Insurance Company', 'Liberty Specialty Markets', 'Esurance', 'Nationwide Agribusiness Insurance Company', 'Generali', 'Kinsale Insurance', 'Guarantee Company Of North America Usa (The)', 'NAPLSO', 'EmblemHealth', 'Gorst & Compass', 'Premera Blue Cross', 'Universal Insurance Company', 'Neptune', 'W. R. Berkley Corporation', 'Western Pacific Insurance Network, Inc.', 'Safety National', 'St. Paul Guardian Insurance Company', 'United Casualty And Surety Insurance Company', 'Endurance American Insurance Company', 'CFC Underwriting', 'WTW', 'PEACHTREE SPECIAL RISK BROKERS, LLC', 'MS Amlin', 'American Strategic Insurance (ASI)', 'CNA', 'American International Group (AIG)', 'Pennsylvania Manufacturers Indemnity Company', 'State Compensation Insurance Fund', 'AEU', 'Westport Insurance Corporation', 'Ameriprise Financial', 'Intact', 'Starnet Insurance Company', 'Arbella Insurance Group', 'Safety National Casualty Corporation', 'Hiscox', 'Principal Financial Group', 'Thimble Insurance Services', 'Applied Systems', 'Xl Specialty Insurance Company', 'Fidelity And Deposit Company Of Maryland', 'UnitedHealthcare', 'Risk Placement Services', 'Fcci Insurance Company', 'SELECTIVE INSURANCE GROUP INC.', 'Great American Insurance Company', 'Arch Insurance Company', 'Blue Cross Blue Shield', 'TIAA', 'National Flood Insurance Program', 'American National Insurance Company', 'Wright Flood', 'Bass Underwriters', 'Erie Insurance', 'Beazley Insurance Company, Inc.', 
              'United American Insurance Company', 'Travelers Indemnity Company (The)', 'Brown & Brown', 'National American Insurance Company', 'Ngm Insurance Company', 'Selective Insurance Company Of America', 'Ohio Indemnity Company', 'Penn Mutual', 'Oklahoma Surety Company', 'Bitco General Insurance Corporation', 'Health Care Service Corporation (HCSC)', 'Navigators Insurance Company', 'General Star National Insurance Company', 'Travelers', 'GMAC Insurance', 'Amerisure Mutual Insurance Company', 'PEMCO', 'Employers Mutual Casualty Company', 'Kaiser Permanente', 'Roche Surety And Casualty Company, Inc.', 'Berkley National Insurance Company', 'Endurance Assurance Corporation', 'Metromile', 'New York Life', 'CID Insurance Programs', 'John Hancock Life Insurance', 'Burns & Wilcox', 'California Earthquake Authority (CEA)', 'National Fire & Marine Insurance Company', 'West American Insurance Company', 'Zurich', 'Unitrin', 'State Auto Property And Casualty Insurance Company', 'Brierfield Insurance Company', 'First Founders Assurance Company', "Lloyd's of London", 'Protective Property & Casualty Insurance Company', 'Great American Security Insurance Company', 'Colonial American Casualty And Surety Company', 'Allied World', 'Fidelity And Guaranty Insurance Underwriters, Inc.', 'Carolina Casualty Insurance Company', 'Liberty Mutual Fire Insurance Company', 'Bold Penguin', 'FISIF-Food Industry Self-Insurance Fund', 'Smart Choice', 'Lexington', 'Western Pacific Mutual Insurance Company', 'Insurance Company Of The West', 'Lemonade Insurance', 'Attune', 'CNA Insurance', 'New Jersey Manufacturers Insurance Company', 'Indemnity National Insurance Company', 'Oxford Health Plans', 'Farmers Alliance Mutual Insurance Company', 'State Auto Insurance', 'Auto-Owners Insurance', 'Starstone National Insurance', 'First Onsite Property Restoration', 'Federal Insurance Company', 
              'National Union Fire Insurance Company Of Pittsburgh, Pa', 'Rockwood Casualty Insurance Company', 'HBW (Hull & Company)', 'UnitedHealth Group', 'Ohio Casualty Insurance Company (The)', 'Great American Insurance Group', 'Redpoint County Mutual Company', 'Farmers Insurance Group', 'Ryan Turner Specialty', 'Charity First', 'St. Paul Mercury Insurance Company', 'Evergreen National Indemnity Company', 'Manulife', 'Transatlantic Reinsurance Company', 'WSIA', 'Standard Fire Insurance Company (The)', 'Nationwide', 'American Automobile Association (AAA)', 'Colonial Life & Accident Insurance Company', 'GuideOne Insurance', 'Acuity', 'Bright Health', 'InsurBanc', 'All Risks Limited', 'Munich Re', 'Hartford Accident And Indemnity Company', 'Pacific Indemnity Company', 'HealthMarkets', 'Molina Healthcare', 'Hartford', 'AXA Equitable Life Insurance Company', 'ING Group', 'American Family Insurance', 'Colonial Penn', 'Mesa Underwriters Specialty Insurance', 'Zurich North America', 'One Beacon', 'National Fire Insurance of Hartford', 'Aon', 'Ascot Surety & Casualty Company', 'Legal & General', 'Siriuspoint America Insurance Company', 'Old Republic', 'Mercury Insurance', 'PIE Insurance', 'Berkshire Hathaway (GUARD Insurance Companies)', 'Philadelphia Insurance Company', 'Burns and Wilcox', 'Amica Mutual Insurance', 'Southern Aid and Insurance Company', 'Fidelis Care', 'NIF Group', 'Imt Insurance Company', 'Liberty Mutual', 'Accenture', 'Auto-Owners Insurance Company', 'PROPELLER BONDS', 'Encompass Insurance Company', "Kentucky Employers' Mutual Insurance", 'Society Insurance', 'Commerce Insurance Group', 'Kemper Corporation', 'American Income Life Insurance Company', 'Safeco', 'Financial Casualty & Surety, Inc.', 'Canopius', 'Humana', 'Swiss Re', 'Chubb Corp', 'Trupanion', 'Cigna', 'K&K Insurance', 'Merchants Insurance Group', 'MassMutual', 'Great American Insurance Company Of New York', 'Howden', 'Travelers Casualty Insurance Company Of America', 'Travelers Property Casualty Company Of America', 'Frankenmuth Insurance Company', 'American Road Insurance Company (The)', 'Allied World Insurance Company', 'The Norfolk & Dedham Group', 'Cumis Specialty Insurance Company, Inc.', 'Granite State Insurance Company', 'Encompass Insurance', 'Brit', 'Health Net', 'Mercer', 'MetLife Auto & Home®', 'Bankers Life and Casualty', 'Puerto Rico State Insurance Fund', 'Stillwater Insurance Services, Inc.', 'State Automobile Mutual Insurance Company', 'Mercer Insurance Group', 'MetLife', 'Guardian Life', 'Medical Mutual of Ohio', 'The Regence Group', 'Crawford & Company', 'Risk Placement Service', 'NAS Insurance', 'AmWins', 'American Guarantee And Liability Insurance Company', 'Pacific Life', 'Argo Group', 'Hyperion Insurance Group', 'Texas Mutual', 'COVER Financial', 'Berkley', 'Oak Street', 'Service Insurance Company Inc. (The)', 'General Casualty Company Of Wisconsin', 'AmTrust Financial Services, Inc.', 'WellCare', 'Smart Choice Agents', 'ARS', 'Progressive Casualty Insurance Company', 'Tricare', 'Hanover Insurance', 'First Insurance Company of Hawaii', 'Compass Rose Benefits Group', 'MassHealth', 'RT Specialty', 'International Excess', 'Philadelphia Contributionship for the Insurance of Houses from Loss by Fire', 'Zurich American Insurance Company', 'Front Row Insurance', 'Century Insurance', 'Markel Insurance Company', 'Westchester Fire Insurance Company', 'General Re', 'Ironshore', 'Hanover Insurance Company (The)', 'QBE', 'American Surety Company', 'Lexington National Insurance Corporation', 'Conseco', "Lloyd's", 'National Life Group', 'Infinity Insurance', 'Berkley Insurance Company', 'AmWINS Brokerage', 'The Institutes', 'Evergreen USA RRG', 'Gray Casualty & Surety Company (The)', 'United of Omaha', 'National Program Administrators', 'Missouri Employers Mutual', 'Sentry Insurance Company', 'Capitol Indemnity Corporation', 'American Contractors Indemnity Company', 'RLI Insurance Company', 'Continental Casualty Company', 'Atlantic Specialty Insurance Company', 'First American', 'Great Midwest Insurance Company', 'Penn National Insurance', 'Orchid', 'Cambia Health Solutions', 'RLI Surety', 'Suretec Insurance Company', 'AXA', 'HCC Specialty', 'GIG Insurance Group', 'AmGUARD', 'ECC Insurance Brokers, LLC', 'AXA XL', 'ProSight Specialty Insurance', 'Vigilant Insurance Company', 'Lincoln Financial Group', 'AmTrust Financial Services', 'Crum & Forster Specialty Insurance Company', 'Hagerty Insurance Agency', 'Zurich Insurance Group', 'Reliance Partners', 'Federated Mutual Insurance Company', 'GUARD Insurance Group', 'Mid-Century Insurance Company', 'Berkley Regional Specialty Insurance Company', 'Motors Insurance Corporation', 'Procentury Insurance Company', 'Ironshore Indemnity Inc.', 'Union Insurance Company', 'Cincinnati Financial Corporation', 'CTC Transportation', 'Arch Reinsurance Company', 'Geisinger', 'Highmark', 'Protective Insurance Company', 'Kansas City Life Insurance Company', 'Chesapeake Employers Insurance', 'Financial Pacific Insurance Company', 'Acstar Insurance Company', 'ASI (American Strategic Insurance)', 'Ameriprise Auto & Home Insurance', 'American Modern Insurance Group', 'Travelers Texas MGA', 'Garden State Life', 'Bond Safeguard Insurance Company', 'Hartford Fire Insurance Company', 'Arch Insurance', 'Cherokee Insurance Company', 'Fallon Health', 'Lincoln National Corporation', 'RFIB', 'Centennial Casualty Company', 'Independence Blue Cross', 'Utica Mutual Insurance Company', 'Lockton Companies', 'CannGen Insurance Services', 'Aflac', 'Tokio Marine', 'DUAL', 'Marshberry', 'Zenith Insurance Group', 'Gallagher Bassett', 'Cincinnati Indemnity Company, The', 'New Heights Insurance Solutions', 'Ohio Farmers Insurance Company', 'New York State Insurance Fund', 'Michigan Millers Mutual Insurance Company', 'Progressive Northwestern Insurance Company', 'Wright National Flood Insurance Company', 'Genworth', 'HCC Insurance Holdings', 'Beazley', 'Pathpoint', 
              'Erie Insurance Group', 'Harvard Pilgrim Health Care', 'Worldwide Facilities', 'Protective Life', 'Privilege Underwriters Reciprocal Exchange (PURE)', 'Westfield Insurance Company', 'State Farm Fire And Casualty Company', 'SIAA', 'Arthur J. Gallagher', 'Swiss Reinsurance America Corporation', 'Foremost Insurance Group', 'Transamerica Corporation', 'Breckenridge Insurance Services', 'Aetna', 'Fair American Insurance And Reinsurance Company', 'St. Paul Fire And Marine Insurance Company', 'West Bend Insurance Company', 'Horace Mann Educators Corporation', 'Manufacturers Alliance Insurance Company', 'Unum', 'Berkley Asset Protection', 'Continental Heritage Insurance Company', 'Brown & Riding', 'Hdi Global Select Insurance Company', 'CNA Surety', 'Massachusetts Bay Insurance Company', 'AGCS', 'Mountain States Mutual Casualty Company', 'Charter Oak Fire Insurance Company (The)', 'Assurant', 'Executive Risk Indemnity Inc.', 'New Hampshire Insurance Company', 'General Reinsurance Corporation', 'Trisura', 'Cumis Insurance Society, Inc.', 'Acuity Insurance', 'Verterra Insurance Company', 'NJM Insurance Group', 'Ryan Specialty Group', 'Axis Reinsurance Company', 'Accident Fund Insurance Company of America', 'Rli Insurance Company', 'RKH Specialty', 'Allied World Specialty Insurance Company', 'National Fire Insurance Company Of Hartford', 'FM Global', 'Inland Insurance Company', 'Surety Placement Services, LLC', 'Merchants National Bonding, Inc.', 'Combined Insurance', 'Blue Cross and Blue Shield Association', 'Granite Re, Inc.', 'Lexon Insurance Company', 'Specialty Market Insurance Consultants, Inc.', 'FIRST CONNECT', 'NEXT Insurance', 'QBE Insurance Corporation', 'Bankers Life and Casualty Company', 'American Home Assurance Company', 'State Farm Insurance', 'Aspen American Insurance Company', 'United States Fire Insurance Company', 'Transamerica', 'The Guardian Life Insurance Company of America', 'New York Life Insurance Company', 'Allianz', 'Delta Dental', 'USLI', 'Great American Alliance Insurance Company', 'Partner Reinsurance Company Of The U.S.', 'Agency Network Exchange', 'Everest Reinsurance Company', 'National Casualty Company', 'The Travelers Companies', 'Prudential Financial', 'SCOR', 'General Star', 'Antilles Insurance Company', 'Donegal', 'National Indemnity Company', 'Kemper', 'Motorists Mutual Insurance Company', 'Applied Underwriters', 'First Net Insurance Company', 'Southwest Insurance Group', 'American Fire And Casualty Company', 'Berkshire Hathaway Specialty Insurance Company', 'Securian Financial Group', 'Citizens Property Insurance Corporation', 
              'American Fidelity Assurance', 'Thrivent Financial for Lutherans', 'HDI', 'Summit', 'AmWINS Access Insurance', 'Sedgwick', 'Munich Reinsurance America, Inc.', 'GEICO', 'Gallagher', 'Assurity Life Insurance Company', 'NEW MEXICO FAIR PLAN', 'Omega', 'AXIS Capital', 'NFP Property & Casualty Services, Inc.', 'Berkshire Hathaway', 'MEGA Life and Health Insurance', 'British American Insurance Company', 'Irwin Siegel Agency, Inc.', 'American Casualty Company Of Reading, Pennsylvania', 
               'Western Surety Company', 'Chubb', 'Apogee Insurance Group', 'Ameritas Life Insurance Company', 'Bankers Standard Insurance Company', 'Philadelphia Indemnity Insurance Company', 'Progressive', 'Hudson Insurance Company', 
               'Modern Woodmen of America', 'GAINSCO', 'Mercury County Mutual - TX', 'Allianz Life', 'SquareTrade', 'UNIFI Companies', 'Allied Property And Casualty Insurance Company', 'ITC', 'Gray Insurance Company (The)', 'Berkshire Hathaway Inc.', 'Developers Surety And Indemnity Company', 'Fidelity And Guaranty Insurance Company', 'Cincinnati Insurance', 'PURE Insurance', 'Allegheny Casualty Company', 'Farmington Casualty Company', 'Mid-Continent Casualty Company', 'UPC Insurance', 'Allied Insurance', 'Continental Insurance Company (The)', 'U.S. Specialty Insurance Company', 'Safeco Insurance', 'Seneca Insurance Company, Inc.', 'Pure Insurance', 'Amco Insurance Company', 'Aspen', 'Centene Corporation', 'Surety Bonding Company Of America', 'State Farm', 'Physicians Mutual', 'Insurance Company Of North America', 'Star Insurance Company', 'XL Catlin', 'Clearcover Insurance Company', 'Qbe Insurance Corporation', 'SPECIAL MARKETS INSURANCE CONSULTANTS', 'HealthPartners', 'Banner Life Insurance Company', 'Contractors Bonding And Insurance Company'
               ]


print(len(final_list))
